export default {
  extends: ['@commitlint/config-conventional'],
  formatter: '@commitlint/format',
  rules: {
    'subject-max-length': [2, 'always', 100],
    'subject-case': [2, 'never'],
    'scope-empty': [2, 'never'],
    'scope-case': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'assets',
        'authentication',
        'components',
        'composables',
        'config',
        'constants',
        'core',
        'dependencies',
        'directives',
        'documentation',
        'infrastructure',
        'interfaces',
        'internationalization',
        'layout',
        'locales',
        'middlewares',
        'mocks',
        'pages',
        'plugins',
        'public',
        'readme',
        'release',
        'security',
        'services',
        'stores',
        'styles',
        'testing',
        'todo',
        'types',
        'ui',
        'utils',
        'validations',
        'views',
        'vscode',
      ],
    ],
  },
  ignores: [(commit: string) => commit === ''],
  defaultIgnores: true,
  helpUrl: 'https://github.com/conventional-changelog/commitlint/#what-is-commitlint',
  prompt: {
    messages: {},
    questions: {
      type: {
        description: 'please input type:',
      },
    },
  },
}
